name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  push_to_registry:
    # Use CI environment secrets
    environment: "Continuous Integration"
    
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: tkreind
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push massif-visualizer
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./.devcontainer/
          file: ./.devcontainer/base.Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=tkreind/dotnet-devcontainer:latest
          cache-to: type=inline
          tags: tkreind/dotnet-devcontainer:latest
